/**
 * 把一些通用的提示抽出，保持系统一致
 * @type 
 */
var Msg={
	saveConfirm:"确定保存？",
	saveSuc:"保存成功！",
	delSuc:"删除成功！",
	operateSuc:"操作成功！",
	submitting:"正在提交，请稍后...",
	delconfirm:"确定删除所选记录？",
	cancelconfirm:"确定注销所选记录？",
	hascanceled:"该人员已注销！",
	reportSuc:"上报成功！",
	cancelSuc:"注销成功！",
	sfzExist:"该身份证号已存在！",
	sfzNotExist : "该身份证号不存在，请先登记！",
	sfzneed : "请输入身份证！",
	bfrqneed : "请选择补发日期！",
	sfzNotOk:"该老人年龄不满足登记条件！",
	sfzDoBf:"保存成功！是否给该老人补发？",
	yearnotok : "补发时间不能跨年！",
	hasbf : "该时间段已补发过！",
	atLeastCheckOne:"请至少选中一条数据！",
	noMoreThanOne:"一次只能选中一条数据！",
	bufasuccess : "补发成功！",
	bufaconfirm : "确认给该老人补发？",
	sfqbzt : "确认全部暂停？",
	qbztcg : "全部暂停成功",
	qrfh : "确认复核？",
	qrhf : "确认恢复？",
	dukafirst : "请先读卡",
	putinsfz : "请放入身份证",
	noreadcardobj : "未检测到读卡设备",
	bfnybnwk : "请选择补发时间",
	xsrsfz : "请先输入身份证",
	mustChooseSq : "所属地区必须选择到社区",
	spSuc : "已审批",
	spFal : "审批出错",
	nbSuc : "已拟办",
	nbFal : "拟办出错",
	spSuccess:"审批成功！",
	shSuccess:"审核成功！"
};
